### ISSUE TITLE
allow user defined settings

### ISSUE THREAD

**Issue by christianrauch** [ROBOTIS-GIT/ros2arduino#1]
For adjusting the size of the program and dynamic memory, it would be nice if the `UXR_` macros (e.g. `UXR_PACKED_SAMPLES_SEQUENCE_MAX`, ...) could be user-defined.

**Comment by OpusK** [comment]
Hi, @christianrauch 

Thank you for your good feedback. I am also considering this part.

The `` UXR_`` macro you mentioned belongs to the Micro-XRCE-DDS Client library.
I am wondering whether it would be better to ask eProsima officially to allow these definitions to be redefined by the user, or to modify them separately in ros2arduino.

I think we should make a request to eProsima, and if that is difficult, it would be better to consider the second method.

What do you think?

**Comment by christianrauch** [comment]
I overlooked that the XRCE implementation actually comes from eProsima. In this case, it would of course make sense to talk to them first.
In the micro-ROS thread on https://discourse.ros.org/t/rmw-microxrcedds-implementation/6727 I was actually asking for their plans to support low-end MCUs like the ATmega328. I haven't heard back from them, but I guess they wouldn't mind to have their XRCE implementation more configurable and running on low-end MCUs.

Do you actually plan to have `ros2arduino` work on the lower-end range of Arduino boards that use the ATmega328 (Micro, Nano, Mini)?

**Comment by OpusK** [comment]
> Do you actually plan to have ros2arduino work on the lower-end range of Arduino boards that use the ATmega328 (Micro, Nano, Mini)?

Apart from the possibility, I have the plan. In order to do this, it seems that the order is to change the size of the buffers of the Micro-XRCE-DDS Client library and to check that there are no problems in operation.

And to make it more flexible and easier for the user to change, it would be nice to allow the user to override the buffer size as you mentioned.

**Comment by OpusK** [comment]
@christianrauch,

I have raised an issue with eProsima regarding this issue.
 - [Allow user defined settings](https://github.com/eProsima/Micro-XRCE-DDS-Client/issues/61#issuecomment-448599836)

Most of the definitions in internal.h are protocol-related and should not be modified.

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
