### ISSUE TITLE
Problems creating second Publisher

### ISSUE THREAD

**Issue by fan4tix** [ROBOTIS-GIT/ros2arduino#26]
Hi there, 
thanks for this very useful project. I am using it for my masters thesis and unfortunately I have a problem. 

I am having trouble creating more than one Publisher on the NodeMCU. I am working with a Raspberry Pi 3B Running Ubuntu 18.04 64-Bit, Crystal, v0.9 of the library from github and the 1.0.1 version of the DDS agent. I took the sample code for a serial publisher and added a second publisher. 
``` C
#include <ros2arduino.h>


#define XRCEDDS_PORT  Serial
#define PUBLISH_FREQUENCY 2 //hz
void publishString(std_msgs::String* msg, void* arg)
{
  (void)(arg);

  sprintf(msg->data, "Hello World1" );
}


void publishString2(std_msgs::String* msg, void* arg)
{
  (void)(arg);

  sprintf(msg->data, "Hello World2" );
}

class StringPub : public ros2::Node
{
public:
  StringPub()
  : Node()
  {
    ros2::Publisher<std_msgs::String>* publisher1_ = this->createPublisher<std_msgs::String>("arduino_chatter1");
    ros2::Publisher<std_msgs::String>* publisher2_ = this->createPublisher<std_msgs::String>("arduino_chatter2");
    
    this->createWallFreq(PUBLISH_FREQUENCY, (ros2::CallbackFunc)publishString, NULL, publisher1_);
    this->createWallFreq(PUBLISH_FREQUENCY, (ros2::CallbackFunc)publishString2, NULL, publisher2_);
  }
};

void setup() 
{
  XRCEDDS_PORT.begin(115200);
  while (!XRCEDDS_PORT); 

  ros2::init(&XRCEDDS_PORT);
  
}

void loop() 
{
  static StringPub StringNode;

  ros2::spin(&StringNode);
}
``` 
In this example, the second call to createPublisher returns NULL.
Am I doing this correctly and should this code work under normal conditions? 

Thanks very much in advance for the Help

**Comment by OpusK** [comment]
Hi, @fan4tix 

There may be a problem with the old version. Can you try the latest version?

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
