### ISSUE TITLE
Have you try implement Action on arduino?

### ISSUE THREAD

**Issue by zhaoyun4411** [ROBOTIS-GIT/ros2arduino#38]

**Comment by OpusK** [comment]
Hi, @zhaoyun4411 

I have never tried. There is nothing currently planned.

**Comment by zhaoyun4411** [comment]
Hi, @OpusK 

What about Ros2 service? In my application, most of the task is provided by the service (ask - response). But I try to add `rr/rq/rs` as a topic name prefix seems to me not work. Thanks.

**Comment by OpusK** [comment]
@zhaoyun4411 

As indicated in the README, we currently only support rt (topic).
Since service works differently from topic, it does not work with the current structure.

**Comment by zhaoyun4411** [comment]
Got it thanks
