### ISSUE TITLE
ESP-IDF issue Issue with ucdr/types/string.h

### ISSUE THREAD

**Issue by MS71** [ROBOTIS-GIT/ros2arduino#41]
Hi,
i like to use your library inside a ESP-IDF project together with the arduino-esp32 component.
Any hint?

$ make
Toolchain path: esp-idf-stable/../xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
Python requirements from esp-idf-stable/requirements.txt are satisfied.

CC build/app_trace/host_file_io.o
In file included from esp-idf-stable/components/app_trace/host_file_io.c:25:0:
**esp_uros_test01/components/arduino/libraries/ros2arduino/src/ucdr/types/string.h:1:91: fatal error: ros2/xrcedds/micro_xrce_dds/lib/thirdparty/microcdr/include/ucdr/types/string.h: No such file or directory**
compilation terminated.
esp-idf-stable/make/component_wrapper.mk:289: recipe for target 'host_file_io.o' failed
make[1]: *** [host_file_io.o] Error 1
esp-idf-stable/make/project.mk:552: recipe for target 'component-app_trace-build' failed
make: *** [component-app_trace-build] Error 2

"string.h" doesn't exist at that path.
Same code is compile-able within an original arduino environment. I can't understand why?

**Comment by OpusK** [comment]
Hi, @MS71.

First, sorry, and thanks for your feedback.
The dead code was still included.
I removed this from #42 and will release it later. (No problem in Arduino IDE.)

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
