### ISSUE TITLE
Ros Foxy Release

### ISSUE THREAD

**Issue by olmerg** [ROBOTIS-GIT/ros2arduino#49]
I see in the readme that you are planning to suppoert LTS version, you have a date to release foxy version

**Comment by OpusK** [comment]
Hi, @olmerg 
Thanks for your interest in the ros2arduino library.

I'm planning on releasing it after making [certain issues](https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/171#issue-641652486) clear.

**Comment by OpusK** [comment]
I'm sorry, @olmerg 

Unfortunately, we decided not to plan on supporting ros2arduino beyond the current version (0.2.1).
README will be modified.
