### ISSUE TITLE
ros2arduino for ROS2 Foxy

### ISSUE THREAD

**Issue by irsyadtc** [ROBOTIS-GIT/ros2arduino#67]
Since the latest version of ros2arduino 0.2.1 library is for ROS2 Dashing Diademata Patch6, is there any version or means to use ros2arduino for ROS2 Foxy?

**Comment by irsyadtc** [comment]
For Foxy, please see [micro_ros_arduino](https://github.com/micro-ROS/micro_ros_arduino)

**Comment by tbcky** [comment]
Yes, micro_ros_arduino support ros2 foxy, release of the serial port to receive is implemented, the wifi also can realize announcement on the ros, but on how esp32 subscription ros2 message I have not been able to succeed
If you have any idea, please communicate with me, thank you very much
